# Arkovia mainnet full node. Original genesis files are unchanged.
nxt.isTestnet=false
nxt.isLightClient=false
nxt.enableAPIProxy=false
nxt.launchDesktopApplication=false
nxt.peerServerPort=4874
nxt.shareMyAddress=true
nxt.wellKnownPeers=147.93.138.255:4874;217.216.64.226:4874
nxt.usePeersDb=true
nxt.savePeers=true
nxt.getMorePeers=true
nxt.enableAPIServer=true
nxt.apiServerPort=4876
nxt.apiServerSSLPort=4877
nxt.apiServerHost=127.0.0.1
nxt.allowedBotHosts=127.0.0.1; localhost; [0:0:0:0:0:0:0:1];
nxt.dbDir=./nxt_db/nxt
nxt.includeExpiredPrunable=true
